release ru srs files too

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -47,6 +47,26 @@ jobs:
           go build -C geodat2srs ./
           ./geodat2srs/geodat2srs geoip -i ./publish/geoip.dat -o ./tmp/sing-box/rule-set-geoip/
           ./geodat2srs/geodat2srs geosite -i ./publish/geosite.dat -o ./tmp/sing-box/rule-set-geosite/
+          
+          cp ./tmp/sing-box/rule-set-geoip/geoip-ru* ./publish/
+          cp ./tmp/sing-box/rule-set-geosite/geosite-ru* ./publish/
+          
+          required_files=(
+            "geosite-ru-available-only-inside.srs"
+            "geosite-ru-blocked-all.srs"
+            "geosite-ru-blocked.srs"
+            "geoip-ru-blocked-community.srs"
+            "geoip-ru.srs"
+            "geoip-ru-blocked.srs"
+          )
+          
+          for file in "${required_files[@]}"; do
+            if [ ! -f "./publish/$file" ]; then
+              echo "Error: Required file $file is missing!"
+              exit 1
+            fi
+          done
+          
           cd ./tmp/sing-box || exit 1
           zip -r ../../publish/sing-box.zip *
 
